{% set name = "pytorch-model-summary" %}
{% set version = "0.1.2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pytorch_model_summary-{{ version }}.tar.gz
  sha256: 1008a4b94943f1e534d08889dcf77861beb7796ae7193ab90677e50513c250fe

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - numpy
    - python >=3.6
    - pytorch
    - tqdm

test:
  imports:
    - pytorch_model_summary
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/amarczew/pytorch_model_summary
  summary: It is a Keras style model.summary() implementation for PyTorch
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - fishyai
